---
title: "cacheR"
author: "Peter M. C. Harrison"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r define_function}
cache_root <- tempdir()
cache_dir <- "cache_fun"

fun <- function(
  n,
  msg_start = TRUE,
  msg_end = TRUE,
  cache = TRUE
) {
  cacheR::cache(
    fun_name = "fun",
    cache = cache,
    cache_root = cache_root,
    cache_dir = cache_dir,
    ignore_args = c("msg_start", "msg_end", "cache", "cache_root", "cache_dir"),
    expr = expression({
      if (msg_start) message("Waiting for ", n, " second(s)")
      Sys.sleep(n)
      if (msg_end) message("Finished waiting")
      paste(n, " * ", n, " = ", n * n)
    })
  )
}
```

The first run with n = 1 takes 1 second to run the first time.

```{r}
system.time(print(fun(n = 1)))
```

Subsequent runs with n = 1 take no time to run, because the result has been cached.

```{r}
system.time(print(fun(n = 1)))
system.time(print(fun(n = 1)))
```

Changing n to 0.5 requires recomputing the return value, which takes 0.5 seconds the first time, and 0 seconds on successive repeats.

```{r}
system.time(fun(n = 0.5))
system.time(fun(n = 0.5))
system.time(fun(n = 0.5))
```

Clearing the cache means that the return value needs to be recomputed.

```{r}
cacheR::clear_cache(cache_root = cache_root,
                    cache_dir = cache_dir)
system.time(fun(n = 0.5))
```
